name: Unit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Run go test
      run: go test -v -race -coverprofile coverage.txt -covermode atomic ./...

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
